In [1]:
# W1D3: Data Loading, Cleaning & Inspection

import pandas as pd
import numpy as np
import os


# Create sample dataset
data = {
    "State": [
        "Karnataka",
        "Tamil Nadu",
        "Kerala",
        "Karnataka",
        "Maharashtra"
    ],
    "Population": [
        61000000,
        72000000,
        None,
        61000000,
        112000000
    ],
    "Area": [
        191791,
        130058,
        38863,
        191791,
        307713
    ]
}


df = pd.DataFrame(data)


# Data Inspection
print("Shape:")
print(df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nFirst 10 Rows:")
display(df.head(10))


# Missing value check
print("\nMissing Values:")
print(df.isnull().sum())


# Cleaning missing values
df["Population"] = df["Population"].fillna(
    df["Population"].mean()
)


# Remove duplicates
df = df.drop_duplicates()


# Remove spaces
df["State"] = df["State"].str.strip()


print("\nCleaned Dataset:")
display(df)


# Export files

df.to_csv(
    "cleaned_w1d3_states.csv",
    index=False
)

df.to_parquet(
    "cleaned_w1d3_states.parquet",
    index=False
)


# File size comparison

csv_size = os.path.getsize(
    "cleaned_w1d3_states.csv"
)

parquet_size = os.path.getsize(
    "cleaned_w1d3_states.parquet"
)


print("\nCSV Size:", csv_size, "bytes")
print("Parquet Size:", parquet_size, "bytes")

print("\nW1D3 Completed Successfully!")

Shape:
(5, 3)

Data Types:
State             str
Population    float64
Area            int64
dtype: object

First 10 Rows:

         State   Population    Area
0    Karnataka   61000000.0  191791
1   Tamil Nadu   72000000.0  130058
2       Kerala          NaN   38863
3    Karnataka   61000000.0  191791
4  Maharashtra  112000000.0  307713

Missing Values:
State         0
Population    1
Area          0
dtype: int64

Cleaned Dataset:

         State   Population    Area
0    Karnataka   61000000.0  191791
1   Tamil Nadu   72000000.0  130058
2       Kerala   76500000.0   38863
4  Maharashtra  112000000.0  307713

ImportError: Unable to find a usable engine; tried using: 'pyarrow', 'fastparquet'.
A suitable version of pyarrow or fastparquet is required for parquet support.
Trying to import the above resulted in these errors:
 - `Import pyarrow` failed. pyarrow is required for parquet support. Use pip or conda to install the pyarrow package.
 - `Import fastparquet` failed. fastparquet is required for parquet support. Use pip or conda to install the fastparquet package.